version: '3.4'

services:
  db:
    image: mariadb:10
    ports: 
        - 3306:3306
    environment:
        - MARIADB_ROOT_PASSWORD=secret1234
        - MARIADB_DATABASE=hellodb
        - MARIADB_USER=hellouser
        - MARIADB_PASSWORD=secret1234
  
  frontend:
    image: nginx:alpine
    ports:
        - "8090:8080"
    volumes:
      - ./compose/nginx.conf:/etc/nginx/conf.d/custom.conf:ro
      
  application:
    image: ${DOCKER_REGISTRY-}kitnugs
    build:
      context: .
      dockerfile: KitNugs/Dockerfile
    environment: 
        - TEST_VAR=TEST VARIABLE
        - "Serilog__MinimumLevel__Default=Debug"
        - "ConnectionStrings__db=server=db;user=hellouser;password=secret1234;database=hellodb"
    ports:
        - "8080:8080"
        - "8081:8081"
        
  documentation:
    image: ${DOCKER_REGISTRY-}kitnugs-documentation
    build:
      context: ./Documentation
      dockerfile: docker/Dockerfile
    environment:
      - BASE_URL=/swagger
      - 'SERVER_URLS=[{"url": "http://localhost:8090", "name": "HelloService"}]'
    
