version: '3.4'

services:
  db:
    image: postgres:15
    ports: 
        - 5432:5432
    environment:
        - POSTGRES_PASSWORD=secret1234
        - POSTGRES_DB=hellodb
        - POSTGRES_USER=hellouser
  
  frontend:
    image: nginx:alpine
    ports:
        - "8090:8080"
    volumes:
      - ./compose/nginx.conf:/etc/nginx/conf.d/custom.conf:ro
      
  application:
    image: ${DOCKER_REGISTRY-}kitnugs
    build:
      context: .
      dockerfile: KitNugs/Dockerfile
    environment: 
        - TEST_VAR=TEST VARIABLE
        - "Serilog__MinimumLevel__Default=Debug"
        - "ConnectionStrings__db=Host=db;Database=hellodb;Username=hellouser;Password=secret1234"
    ports:
        - "8080:8080"
        - "8081:8081"
        
  documentation:
    image: ${DOCKER_REGISTRY-}kitnugs-documentation
    build:
      context: ./Documentation
      dockerfile: docker/Dockerfile
    environment:
      - BASE_URL=/swagger
      - 'SERVER_URLS=[{"url": "http://localhost:8090", "name": "HelloService"}]'
    
