version: '3.4'

services:
  db:
    image: postgres:15
    ports: 
        - 3306:3306
    environment:
        - POSTGRES_PASSWORD=secret1234
        - POSTGRES_DB=hellodb
        - POSTGRES_USER=hellouser
  
  kitnugs:
    image: ${DOCKER_REGISTRY-}kitnugs
    build:
      context: .
      dockerfile: KitNugs/Dockerfile
    environment: 
        - TEST_VAR=TEST VARIABLE
        - "Serilog__MinimumLevel__Default=Debug"
        - "ConnectionStrings__db=Host=db;Database=hellodb;Username=hellouser;Password=secret1234"
    ports:
        - "8080:8080"
        - "8081:8081"
