version: '3.4'

services:
  db:
    image: mariadb:10
    ports: 
        - 3306:3306
    environment:
        - MARIADB_ROOT_PASSWORD=secret1234
        - MARIADB_DATABASE=hellodb
        - MARIADB_USER=hellouser
        - MARIADB_PASSWORD=secret1234
  
  kitnugs:
    image: ${DOCKER_REGISTRY-}kitnugs
    build:
      context: .
      dockerfile: KitNugs/Dockerfile
    environment: 
        - TEST_VAR=TEST VARIABLE
        - "Serilog__MinimumLevel__Default=Debug"
        - "ConnectionStrings__db=server=db;user=hellouser;password=secret1234;database=hellodb"
    ports:
        - "8080:8080"
        - "8081:8081"
